### ISSUE TITLE
Export image failed with "file does not contain topic /file_version"

### ISSUE THREAD

**Issue by glennliu** [UnaNancyOwen/rs_bag2image#10]
Hi @UnaNancyOwen 

I run program as the instruction,
   `./rs_bag2image -b="/home/dji/bag/sensors00.bag" -s=true -d=true`
It shows the error,
> rs_bag2image 0.1.3
> [ INFO:0] Initialize OpenCL runtime...
> Failed to create ros reader: Invalid file format, file does not contain topic "/file_version" nor "/FILE_VERSION"

Information for the environment I used,
- OS: Ubuntu 16.04.
- cmake 3.12, librealsense 2.20, opencv 3.2.0

Any suggestion?

Thanks

**Comment by UnaNancyOwen** [comment]
Please share the bag file where that problem occurs.

**Comment by glennliu** [comment]
> Please share the bag file where that problem occurs.

Please download the bag file [here](https://hkustconnect-my.sharepoint.com/:u:/g/personal/cliuci_connect_ust_hk/Ed09e_uCNiRGgAWVK6Da-VQBqiZscMjW2Ld9sXRYtpLD-w?e=VrKRqT).

**Comment by UnaNancyOwen** [comment]
That bag file is broken. It can't be loaded even by RealSense Viewer on my emvironments.
Can you load that bag file on RealSense Viewer?
