### ISSUE TITLE
Error occurs with find_package

### ISSUE THREAD

**Issue by Dennis2Choi** [UnaNancyOwen/rs_bag2image#11]
I just started with run D435i

want to learn about ROS bag file format.

but had a problem with running rs_bag2image with find_package

what should I change CMakeLists.txt

Please help me find a right way to run

Thanks

=====================================================
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "Findrealsense2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "realsense2", but CMake did not find one.

  Could not find a package configuration file provided by "realsense2" with
  any of the following names:

    realsense2Config.cmake
    realsense2-config.cmake

  Add the installation prefix of "realsense2" to CMAKE_PREFIX_PATH or set
  "realsense2_DIR" to a directory containing one of the above files.  If
  "realsense2" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "C:/rs_bag2image/build/CMakeFiles/CMakeOutput.log".
=====================================================

**Comment by ryanayf** [comment]
Did you download the realsense2 SDK? 

In you are in Windows, you can either download the SDK-WIN10.exe or build the source code (with CMake). If you done so, then there will be a ./build inside the folder `librealsense-2.35`. Set the option `realsense_DIR` in CMake GUI as the build folder, such as `C:\Users\librealsense-2.35.2\build` .
