### ISSUE TITLE
Failed to convert .bag to image

### ISSUE THREAD

**Issue by ryanayf** [UnaNancyOwen/rs_bag2image#12]
I was using the pre-built rs_bag2image downloaded from [here](http://unanancyowen.com/en/rs_bag2image/). 
And then I ran the following command:
`./rs_bag2image.exe -b="./20200615_181657.bag" -s=true -d=true`
but it seems cannot output the relative depth and color image, and gave the following verbose:

`rs_bag2image 0.1.1
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info 
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Depth 
Color 
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info`

I am using Windows 10, librealsense-2.35.2, and the image was acquired by Intel RealSense D435.
As I am new to realsense, I appreciate any guides. 

Thank you!

**Comment by UnaNancyOwen** [comment]
First, Please check whether Can be played correctly from your bag file on RealSense Viewer.
And, Please try rs_bag2image with [sample bag files](https://github.com/IntelRealSense/librealsense/blob/master/doc/sample-data.md). If it doesn't work correctly, please share your bag file with us.

**Comment by ochilab** [comment]
I  also faced the same warning. The bag file is from the sample bag files.

`rs_bag2image -b="./stairs.bag" -s=false -d=true
rs_bag2image 0.1.2
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info
Depth
Color
Failed to convert source: "" to matching rs2_camera_info
Failed to convert source: "" to matching rs2_camera_info`

Moreover, the depth images are not 16bit row data in PNG. 
They are 8bit PNG images.

**Comment by UnaNancyOwen** [comment]
@ryanayf @ochilab I noticed that you are using an older version.
Please try-again with [latest version](https://github.com/UnaNancyOwen/rs_bag2image/releases/tag/v0.1.5).

NOTE: current latest version is v0.1.5.

> Moreover, the depth images are not 16bit row data in PNG.
> They are 8bit PNG images.

It is fixed in rs_bag2image v0.1.3 (or later).

**Comment by ochilab** [comment]
Perfect! It worked!!
Thank you for your work.
