### ISSUE TITLE
ビルドエラーが起こりました

### ISSUE THREAD

**Issue by sugioka-ken** [UnaNancyOwen/rs_bag2image#16]
環境
Ubuntu 18.04
Cmake 3.14.1
GCC 8.4.0
```
cd rs_bag2image/rs_bag2image/
mkdir build
cd build/
cmake ..
make
```
上記を実行すると以下のエラーが起こりました。

```
[ 33%] Building CXX object CMakeFiles/rs_bag2image.dir/realsense.cpp.o
[ 66%] Building CXX object CMakeFiles/rs_bag2image.dir/main.cpp.o
[100%] Linking CXX executable rs_bag2image
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::__cxx11::path::path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::filesystem::__cxx11::path::format)':
realsense.cpp:(.text._ZNSt10filesystem7__cxx114pathC2EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS1_6formatE[_ZNSt10filesystem7__cxx114pathC5EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS1_6formatE]+0x4f): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::__cxx11::path::clear()':
realsense.cpp:(.text._ZNSt10filesystem7__cxx114path5clearEv[_ZNSt10filesystem7__cxx114path5clearEv]+0x20): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::__cxx11::operator==(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)':
realsense.cpp:(.text._ZNSt10filesystem7__cxx11eqERKNS0_4pathES3_[_ZNSt10filesystem7__cxx11eqERKNS0_4pathES3_]+0x1f): undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::__cxx11::path::stem() const':
realsense.cpp:(.text._ZNKSt10filesystem7__cxx114path4stemEv[_ZNKSt10filesystem7__cxx114path4stemEv]+0x28): undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::__cxx11::path::extension() const':
realsense.cpp:(.text._ZNKSt10filesystem7__cxx114path9extensionEv[_ZNKSt10filesystem7__cxx114path9extensionEv]+0x28): undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::is_regular_file(std::filesystem::__cxx11::path const&)':
realsense.cpp:(.text._ZNSt10filesystem15is_regular_fileERKNS_7__cxx114pathE[_ZNSt10filesystem15is_regular_fileERKNS_7__cxx114pathE]+0x14): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `RealSense::initializeSave()':
realsense.cpp:(.text._ZN9RealSense14initializeSaveEv[_ZN9RealSense14initializeSaveEv]+0x73): undefined reference to `std::filesystem::__cxx11::path::parent_path() const'
realsense.cpp:(.text._ZN9RealSense14initializeSaveEv[_ZN9RealSense14initializeSaveEv]+0x158): undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
realsense.cpp:(.text._ZN9RealSense14initializeSaveEv[_ZN9RealSense14initializeSaveEv]+0x30c): undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::__cxx11::path::path<char const*, std::filesystem::__cxx11::path>(char const* const&, std::filesystem::__cxx11::path::format)':
realsense.cpp:(.text._ZNSt10filesystem7__cxx114pathC2IPKcS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5IPKcS1_EERKT_NS1_6formatE]+0x73): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
CMakeFiles/rs_bag2image.dir/realsense.cpp.o: In function `std::filesystem::__cxx11::path::path<char [5], std::filesystem::__cxx11::path>(char const (&) [5], std::filesystem::__cxx11::path::format)':
realsense.cpp:(.text._ZNSt10filesystem7__cxx114pathC2IA5_cS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5IA5_cS1_EERKT_NS1_6formatE]+0x6d): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
CMakeFiles/rs_bag2image.dir/build.make:166: recipe for target 'rs_bag2image' failed
make[2]: *** [rs_bag2image] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/rs_bag2image.dir/all' failed
make[1]: *** [CMakeFiles/rs_bag2image.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

見るポイントがわからなかったのでそのままコピペしましたが、よろしくお願いします。

**Comment by UnaNancyOwen** [comment]
おそらくC++17のfilesystemを利用するためのオプションの指定が上手くいってないと思います。
CMakeLists.txtの以下の指定が正しく動いているか、生成されたMakefileに-lstdc++fsが指定されているか確認してください。
（回避策として手動で-lstdc++fsを書き足せばとりあえずはビルドできると思います。）
https://github.com/UnaNancyOwen/rs_bag2image/blob/v0.1.5/rs_bag2image/CMakeLists.txt#L8-L14
https://github.com/UnaNancyOwen/rs_bag2image/blob/v0.1.5/rs_bag2image/CMakeLists.txt#L40-L42

**Comment by sugioka-ken** [comment]
返信ありがとうございます。

添付していただいた指定のCMakeLists.txtは同じなので大丈夫だとは思うのですが、Makefileの-lstdc++fsの確認方法や書き足す場所など教えて頂けますか？　まだ始めたばかりでよくわからないところが多いですがよろしくお願いします。

**Comment by UnaNancyOwen** [comment]
VMにインストールしたUbuntu 20.04 LTSで確認したのですが、とくに問題なく動いてしまいました。
環境は以下の通りです。
* Ubuntu 20.04 LTS
* GCC 9.3.0
* CMake 3.16.3
* OpenCV 4.2.0
* RealSense SDK 2.44.0

セットアップに利用したコマンドは以下の通りです。
* Update Packages
```sh
sudo apt update
sudo apt upgrade
```
* Install Build Tools
```sh
sudo apt install build-essential
sudo apt install git
sudo apt install cmake
sudo apt install cmake-qt-gui
```
* Install OpenCV
```sh
sudo apt install libopencv-dev
```
* Install RealSense SDK
https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md
```sh
sudo apt-key adv --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
sudo add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo focal main" -u
sudo apt-get install librealsense2-dkms
sudo apt-get install librealsense2-utils
sudo apt-get install librealsense2-dev
sudo apt-get install librealsense2-dbg
```
* Clone and Build rs_bag2image
```sh
git clone https://github.com/UnaNancyOwen/rs_bag2image.git
cd rs_bag2image/rs_bag2image
mkdir build
cd build
cmake ..
cmake --build . --config Release
``` 
* Check Run rs_bag2image
https://github.com/IntelRealSense/librealsense/blob/master/doc/sample-data.md
```sh
wget https://librealsense.intel.com/rs-tests/TestData/outdoors.bag
./rs_bag2image -b="./outdoors.bag" -s=true -d=true
cd outdoors
dir
# Color Depth Infrared
cd Depth
dir
# 013048.png 013079.png ...
eog 013048.png
# Show Image
```
![2021-04-29_15h29_45](https://user-images.githubusercontent.com/816705/116510358-bdd65800-a8ff-11eb-84f2-4c6891410cef.png)
![2021-04-29_15h34_08](https://user-images.githubusercontent.com/816705/116510741-5a005f00-a900-11eb-9fca-fd22d028a8d2.png)

**Comment by sugioka-ken** [comment]
Ubuntu 20.04 LTSで確認したら問題なく実行できました。

しかし実際の撮影したrealsense.bagを使用して
``
./rs_bag2image -b="./realsense.bag" -s=true -d=true
``

を実行するとフォルダ


は生成されるのですが肝心の画像（color,depth,infrared)がない状態です。

原因はわかりますでしょうか。

例で紹介されているoutdoors.bagでは問題なくできました。
![Screenshot from 2021-05-03 15-52-29](https://user-images.githubusercontent.com/82132953/116848546-cc867d00-ac27-11eb-9a7f-c10364561be3.png)
![Screenshot from 2021-05-03 15-41-04](https://user-images.githubusercontent.com/82132953/116847910-79f89100-ac26-11eb-8f2e-2f9dc0558324.png)
![Screenshot from 2021-05-03 15-41-11](https://user-images.githubusercontent.com/82132953/116847920-7d8c1800-ac26-11eb-9c73-f83cbb86c715.png)

**Comment by UnaNancyOwen** [comment]
bagファイルが壊れている可能性があります。対象のbagファイルがRealSense Viewerで正常に再生することができるか確認してみましょう。

**Comment by sugioka-ken** [comment]
realsense-viewerで問題なく再生することができました。
容量が大きいと正常に処理できない可能性はありますか？
このbagファイルは1.7GBあります。

![Screenshot from 2021-05-06 12-24-38](https://user-images.githubusercontent.com/82132953/117238965-d3e89900-ae68-11eb-8a6d-9f226cbfac11.png)

**Comment by sugioka-ken** [comment]
何回もすみません。
過去にrealsense D435 で撮影した動画を処理したところ画像を取得できました。

現在使っているデバイスがL515なのでもしかしたら、対応していないということですか？

**Comment by UnaNancyOwen** [comment]
なるほど、rs_bag2imageはRealSense SDK v2.xがリリースされたばかりのころに書いたツールなのでRealSense L515のbagファイルは対応してないかもしれません。

**Comment by sugioka-ken** [comment]
ということは、今現状では画像ファイルの抽出は厳しいですか、、、。

**Comment by UnaNancyOwen** [comment]
@sugioka-ken 
どうやらRealSense L515のbagファイルに含まれるInfraredのStream Indexが0になっているようです。
既存のコードは1以上であることを前提に書いていたためエラーになっていました。
RealSense D400だと1または２だったのですが、RealSense L500はなぜか1ではなく0になっています。（驚きました
こちらのコミット https://github.com/UnaNancyOwen/rs_bag2image/commit/4153cc277edaabbd22a7e6393f530586dd35a6ef で対応したので試してみてください。

**Comment by sugioka-ken** [comment]
buildし直して試してみたのですが、うまくいきませんでした。
前回と違う点はcolorとdepthに関しては１枚だけ画像が抽出され、infaraedは０枚でした。

また抽出されたcolorとdepthの番号がずれていました。
![Screenshot from 2021-05-11 16-44-26](https://user-images.githubusercontent.com/82132953/117780083-40ed9b80-b27a-11eb-9fcf-310715b4d6ee.png)
![Screenshot from 2021-05-11 16-44-35](https://user-images.githubusercontent.com/82132953/117780101-4519b900-b27a-11eb-9e8e-051e20d12f2b.png)
![Screenshot from 2021-05-11 16-44-38](https://user-images.githubusercontent.com/82132953/117780105-45b24f80-b27a-11eb-8ad3-f680fb5f28e1.png)

**Comment by UnaNancyOwen** [comment]
> 前回と違う点はcolorとdepthに関しては１枚だけ画像が抽出され、infaraedは０枚でした。

もう少し修正する必要がありそうですね。

> また抽出されたcolorとdepthの番号がずれていました。

それは正しい挙動です。rs_bag2imageではフレーム番号（rs2::frame::get_frame_number()の値）をファイル名にして画像を書き出します。このフレーム番号は各ストリームで異なるのでそれぞれズレてるのは間違っているわけではありません。

**Comment by UnaNancyOwen** [comment]
@sugioka-ken すみません、修正が漏れてました。
こちらのコミット https://github.com/UnaNancyOwen/rs_bag2image/commit/071418c61d6f9abcefc3dd5b2390d25088cfefcb で修正できたと思います。[ここの修正](https://github.com/UnaNancyOwen/rs_bag2image/commit/071418c61d6f9abcefc3dd5b2390d25088cfefcb#diff-2f1dbb46644e61fd87e729c6e575a26dfb4e0752ca53d8b3cf2a3d25a6f060aaL540-R542)が抜けていました。
リモートの履歴を書き換えてしまったのでローカルのrs_bag2imageを削除して再度git cloneしなおしてください。

**Comment by sugioka-ken** [comment]
うまく処理できました！本当に助かりました。
ありがとうございます。

**Comment by ThomasNing** [comment]
Hi, I have followed instructions and successfully use the command "cmake .." to build the folder and Makefile under the "build" folder. However, after I type the command "cmake --build . --config Release", there is either no prompts in the terminal nor could I see any ./rs_bag2image file under the build directory. Could I know why?
