### ISSUE TITLE
ビルドエラーが起こりました

### ISSUE THREAD

**Issue by gs55** [UnaNancyOwen/rs_bag2image#2]
環境
Ubuntu16.04
Cmake 3.10.3

```
git clone https://github.com/UnaNancyOwen/rs_bag2image.git
cd   ~/rs_bag2image/rs_bag2image
mkdir build
cd build
cmake ..
make 
```
上記の実行をすると以下のエラーが出ます。
```
In file included ~/rs_bag2image/rs_bag2image/realsense.cpp:1:0:
~/rs_bag2image/rs_bag2image/realsense.h:12:22: fatal error: filesystem: No such file or directory
compilation terminated.
CMakeFiles/rs_bag2image.dir/build.make:62: recipe for target 'CMakeFiles/rs_bag2image.dir/realsense.cpp.o' failed
make[2]: *** [CMakeFiles/rs_bag2image.dir/realsense.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rs_bag2image.dir/all' failed
make[1]: *** [CMakeFiles/rs_bag2image.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
よろしくお願いいたします。

**Comment by UnaNancyOwen** [comment]
<code>filesystem</code>が存在しないということはコンパイラが古いのではないでしょうか？
C++17の<code>filesystem</code>が実装されているコンパイラをお使いください。（GCC 8.0以降？）

<code>filesystem</code>の実験的な実装がされているコンパイラ（GCC 5.3以降？）の場合、以下のように書き換えると上手くいくかもしれません。そのさい、コンパイラオプションを追加・変更する必要があると思います。(<code>target_link_libraries( rs_bag2image stdc++fs )</code>？）

```cpp
//#include <filesystem>
//namespace filesystem = std::filesystem;
#include <experimental/filesystem>
namespace filesystem = std::experimental::filesystem;
```

Windows以外の環境で検証していないため確かなアドバイスはできませんが、ご参考になれば幸いです。

**Comment by gs55** [comment]
gcc (GCC) 8.1.0
でビルドしても上記と同じエラーが出ます。

```
//#include <filesystem>
//namespace filesystem = std::filesystem;
#include <experimental/filesystem>
namespace filesystem = std::experimental::filesystem;
```
に書き換えようと思っているのですが、これが記載されているファイル名を教えていただけますでしょうか。

**Comment by UnaNancyOwen** [comment]
最新のコミット 5f7f73b で修正しました。
Ubuntu 16.04 (WSL)、GCC 7.3.0の環境でビルドできることを確認しました。
もう一度、試してみてください。

**Comment by gs55** [comment]
gcc8.1.0の場合ですが、makeした際に今までとは違うエラーが出ています。

'''
~/rs_bag2image/rs_bag2image/rs_bag2image/realsense.cpp: In constructor ‘RealSense::RealSense(int, char**)’:
~/rs_bag2image/rs_bag2image/rs_bag2image/realsense.cpp:11:37: error: ‘RS_BAG2IMAGE_VERSION’ was not declared in this scope
     std::cout << "rs_bag2image " << RS_BAG2IMAGE_VER
                                     ^
CMakeFiles/rs_bag2image.dir/build.make:62: recipe for target 'CMakeFiles/rs_bag2image.dir/realsense.cpp.o' failed
make[2]: *** [CMakeFiles/rs_bag2image.dir/realsense.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rs_bag2image.dir/all' failed
make[1]: *** [CMakeFiles/rs_bag2image.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
'''
よろしくお願いいたします。

**Comment by UnaNancyOwen** [comment]
4a94eac でどうでしょうか？
お手数ですが、もう一度ご確認ください。

**Comment by gs55** [comment]
ビルドできました。
ありがとうございました。

**Comment by UnaNancyOwen** [comment]
ご確認いただきありがとうございます。
不具合などありましたら、お気軽にお問い合わせください。
