### ISSUE TITLE
Using Boost Filesystem

### ISSUE THREAD

**Issue by jakirkham** [UnaNancyOwen/rs_bag2image#3]
As another option, would it be possible to use Boost Filesystem?

**Comment by UnaNancyOwen** [comment]
I have not investigated the compatibility between Boost.Filesystem and C++ 17 filesystem yet, but I think it is not difficult to support Boost.Filesystem.
If they have full API compatibility, it just define <code>namespace filesystem = boost::filesystem</code> in rs_bag2image/realsense.h.
