### ISSUE TITLE
rs_bag2image can't find the files

### ISSUE THREAD

**Issue by nevynwong** [UnaNancyOwen/rs_bag2image#4]
hello,

When I use CMAKE-GUI to make the rs-bag2image, I found in the CMakeList.txt , librealsense2 package shoule be package from the path("C:/Program Files/librealsense2/lib/cmake/realsense2"),but the files in the SDK 2.0 can't be found, so how to solve it?

Thank you,

**Comment by UnaNancyOwen** [comment]
Pre-built packages of RealSense SDK 2.x that distributed on GitHub release page does not support CMake.
You need build and install RealSense SDK 2.x from source code yourself.
