### ISSUE TITLE
get_frame_number is different between color and depth

### ISSUE THREAD

**Issue by AndyYangMao** [UnaNancyOwen/rs_bag2image#5]
Hi, 
I use the program to extract the color image and the depth image from a single .bag file and it works well.
however, I noticed that the index number is different between color and depth,
for example, color frames start from 057625.jpg 057626.jpg ...
but the depth frames start from 057983.jpg 057984.jpg ...
and most import of all is the total image number is not equal, in my case, there are 641 color frames but 645 depth frames.

I traced the code in creating the index, it comes from get_frame_number()

is there any solution about this? thanks

**Comment by UnaNancyOwen** [comment]
I think it is not synchronized frame number of color and depth.
It is the specification of RealSense. You can ask about it in [RealSense SDK repository](https://github.com/IntelRealSense/librealsense) or [RealSense forum](https://forums.intel.com/s/topic/0TO0P00000018NTWAY/intel-realsense-technology?language=en_US).
If you got useful knowledge by asking there, Please let me. Thanks,
