### ISSUE TITLE
bag2image save depth frames from bag file without colors

### ISSUE THREAD

**Issue by frankfalse** [UnaNancyOwen/rs_bag2image#7]
I have opened this issue because I need to solve the problem with the tool **rs-convert** explained in the issue https://github.com/IntelRealSense/librealsense/issues/3297#issue-412515606.
Frank

**Comment by frankfalse** [comment]
@UnaNancyOwen I'm trying to use **rs_bag2image** tool to extract depth frame from a bag file.
I obtain png files in less time than with the librealsense tool called "rs-convert".
The problem is that the png files from "rs-convert" are colorized, instead png files obtain by rs_bag2image are black and white.

I tried to modify rs_bag2image adding the colorize process present in rs-convert, that means adding the following instruction:
frame = _colorizer.process(frame);
but this is not enough to have the same result of rs-convert.

Could you help me?

Frank

**Comment by UnaNancyOwen** [comment]
If you want depth image that colored with RealSense SDK, Please change source code as follows.
The visualization method is depends on each person involved. (In my case, it is mapped to 0-255 from 0-10000.) I think it's fine if you just do it how you want to.

```patch
  // Draw Depth
  inline void RealSense::drawDepth()
  {
      if( !depth_frame ){
          return;
      }

+     // Apply Color Map
+     rs2::colorizer colorizer;
+     depth_frame = depth_frame.apply_filter( colorizer );

      // Create cv::Mat form Depth Frame
-     depth_mat = cv::Mat( depth_height, depth_width, CV_16UC1, const_cast<void*>( depth_frame.get_data() ) ).clone();
+     depth_mat = cv::Mat( depth_height, depth_width, CV_8UC3, const_cast<void*>( depth_frame.get_data() ) ).clone();
  }
```
```patch
  // Show Depth
  inline void RealSense::showDepth()
  {
      if( !depth_frame ){
          return;
      }

      if( depth_mat.empty() ){
          return;
      }

-     // Scaling
-     cv::Mat scale_mat;
-     depth_mat.convertTo( scale_mat, CV_8U, -255.0 / 10000.0, 255.0 ); // 0-10000 -> 255(white)-0(black)

      // Show Depth Image
-     cv::imshow( "Depth", scale_mat );
+     cv::imshow( "Depth", depth_mat );
  }
```
```patch
  // Save Depth
  inline void RealSense::saveDepth()
  {
      if( !depth_frame ){
          return;
      }

      if( depth_mat.empty() ){
          return;
      }

      // Create Save Directory and File Name
      std::ostringstream oss;
      oss << directory.generic_string() << "/Depth/";
      oss << std::setfill( '0' ) << std::setw( 6 ) << depth_frame.get_frame_number() << ".png";

-     // Scaling
-     cv::Mat scale_mat = depth_mat;
-     if( scaling ){
-         depth_mat.convertTo( scale_mat, CV_8U, -255.0 / 10000.0, 255.0 ); // 0-10000 -> 255(white)-0(black)
-     }

      // Write Depth Image
-     cv::imwrite( oss.str(), scale_mat );
+     cv::imwrite( oss.str(), depth_mat );
  }
```

**Comment by frankfalse** [comment]
Thanks @UnaNancyOwen your program faster than rs-convert but with your modification it suffers of the same problem that I have shown in the issue https://github.com/IntelRealSense/librealsense/issues/3297#issue-412515606.

An help is appreciated!!!
